package com.ExceptionHandling;

public class FinallyNotwork {

	public static void main(String[] args) {
		try{
			double div = 15/0;
		
		
	
		}
		catch(Exception e){
			System.out.println(e. getStackTrace());
			
		
		System.exit(5  );
		}
		finally {
			System.out.println("finally");
			
		}
	}

	
		
	}
	

		
		
		
		  
	
		
		 
		  
	     


